pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                sh 'mvn clean compile'
            }
        }
        stage('Test') {
            steps {
                echo 'Running Tests...'
                sh 'mvn test'
            }        
        }
        stage('Deploy') {
            steps {
                echo 'Deploying (using rsync)...'
                sh """
                rsync -avz --delete \
                /usr/local/dev/ \
                user@100.23.32.19:/usr/local/super_app/
                """
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
            sh 'rm -f tmp/*.dmx' 

    junit(testResults: 'target/surefire-reports/*.xml', allowEmptyResults: true)
        }
        success {
            echo 'Build succeeded!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
